{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyPAa7JQsftmY9Au6JCzTrOI",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/akhaykin/DATA-602/blob/main/Data_602_Assignment_5_py.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "xGc3iOrpyloD"
      },
      "outputs": [],
      "source": [
        "'''\n",
        "Assignment #5\n",
        "1. Add / modify code ONLY between the marked areas (i.e. \"Place code below\") \n",
        "2. Run the associated test harness for a basic check on completeness. A successful run of the test cases does not guarantee accuracy or fulfillment of the requirements. Please do not submit your work if test cases fail.\n",
        "3. To run unit tests simply use the below command after filling in all of the code:\n",
        "    python 05_assignment.py\n",
        "  \n",
        "4. Unless explicitly stated, please do not import any additional libraries but feel free to use built-in Python packages\n",
        "5. Submissions must be a Python file and not a notebook file (i.e *.ipynb)\n",
        "6. Do not use global variables\n",
        "'''\n",
        "\n",
        "\n",
        "import numpy as np, pandas as pd, matplotlib.pyplot as plt\n",
        "import unittest\n",
        "import requests\n",
        "import json\n",
        "\n",
        "def exercise01():\n",
        "    df = None\n",
        "    '''\n",
        "    Create a DataFrame df with 4 columns and 3 rows of data in one line of code. The data can be arbitrary integers.\n",
        "    For example\n",
        "    \n",
        "               0  1  2   3\n",
        "            0  1  2  3   4\n",
        "            1  5  6  7   8\n",
        "            2  7  8  9  10\n",
        "    '''\n",
        "\n",
        "\n",
        "    # ------ Place code below here \\/ \\/ \\/ ------\n",
        "    # simple list of lists as source for the dataframe\n",
        "    data = [[1,2,3,4], [5,6,7,8], [7,8,9,10]]\n",
        "    df = pd.DataFrame(data)\n",
        "   \n",
        "    # ------ Place code above here /\\ /\\ /\\ ------\n",
        "\n",
        "\n",
        "    return df\n",
        "#exercise01()\n",
        "\n",
        "def exercise02(a):\n",
        "    # The function exercise02() receives a Python list and converts it to an ndarray. \n",
        "    # Convert the list to a numpy ndarray called array.\n",
        "\n",
        "\n",
        "    # ------ Place code below here \\/ \\/ \\/ ------\n",
        "    array = np.asarray(a)\n",
        "    print(type(array))\n",
        "    \n",
        "    # ------ Place code above here /\\ /\\ /\\ ------\n",
        "\n",
        "    return array\n",
        "\n",
        "def exercise03(a):\n",
        "    # The function exercise03() receives an ndarray of integers. Return the sum of those integers using NumPy.\n",
        "\n",
        "\n",
        "    # ------ Place code below here \\/ \\/ \\/ ------\n",
        "    sum = np.sum(a)\n",
        "    print('In Exercise 3 sum is', sum)\n",
        "\n",
        "    # ------ Place code above here /\\ /\\ /\\ ------\n",
        "    return sum\n",
        "\n",
        "def exercise04(a):\n",
        "    # The function exercise04() receives an ndarray matrix (2D) of integers. \n",
        "    # Return the sum of the 2nd column using NumPy.\n",
        "\n",
        "\n",
        "    # ------ Place code below here \\/ \\/ \\/ ------\n",
        "    sum = None\n",
        "    sum = np.sum(a[:, 1])\n",
        "    print(f'The sum of column 2 at index 1 for {a} is {sum}')\n",
        "\n",
        "    # ------ Place code above here /\\ /\\ /\\ ------\n",
        " \n",
        "    return sum\n",
        "\n",
        "    def exercise05(n):\n",
        "    # The function exercise05() receives an integer n. Return an ndarray filled with zeros of size n x n (n rows, n columns)\n",
        "\n",
        "\n",
        "    # ------ Place code below here \\/ \\/ \\/ ------\n",
        "    zeros = np.zeros([n, n], dtype=int)   \n",
        "    print(f'In exercise 5 zeros are {zeros}')\n",
        "\n",
        "    # ------ Place code above here /\\ /\\ /\\ ------\n",
        "\n",
        "    return zeros\n",
        "\n",
        "    def exercise06(n):\n",
        "    # The function exercise06() receives an integer n. Return an ndarray filled with ones of size n x n (n rows, n columns)\n",
        "\n",
        "\n",
        "    # ------ Place code below here \\/ \\/ \\/ ------\n",
        "    ones = np.ones([n, n], dtype=int)   \n",
        "    print(f'In exercise 6 ones are {ones}')\n",
        "\n",
        "\n",
        "    # ------ Place code above here /\\ /\\ /\\ ------\n",
        "    \n",
        "    return ones\n",
        "\n",
        "    def exercise07(sd,m,s):\n",
        "    '''The function exercise07() receives integers sd, m, s \n",
        "    which are standard deviation, mean and size respectively. \n",
        "    Return an ndarray filled with s random numbers conforming to a normal \n",
        "    distribution of standard deviation = sd and mean = m\n",
        "    '''\n",
        "    \n",
        "    # ------ Place code below here \\/ \\/ \\/ ------\n",
        "\n",
        "    random_numbers = np.random.normal(m, sd, s)\n",
        "    \n",
        "    # ------ Place code above here /\\ /\\ /\\ ------\n",
        "    \n",
        "    return random_numbers\n",
        "\n",
        "    def exercise08():\n",
        "    '''\n",
        "    Load the CSV data from https://tinyurl.com/y63q7okz into a DataFrame\n",
        "    # Return the following items:\n",
        "    - row_count - Total # of rows\n",
        "    - avg_sq_ft - Average square feet across all transactions\n",
        "    - df_zip_95670 - DataFrame containing all transactions in zip code 95670\n",
        "    - df_zip_not_95610 - DataFrame containing all transactions not in zip code 95610\n",
        "    '''\n",
        "\n",
        "\n",
        "    # ------ Place code below here \\/ \\/ \\/ ------\n",
        "    #read the data from the Sacramento real estate file\n",
        "    #df =  pd.read_csv(\"sacramentorealestatetransactions.csv\", header=0)\n",
        "    df =  pd.read_csv(\"https://tinyurl.com/y63q7okz\", header=0)\n",
        "    print(df.shape)\n",
        "    #print(df.head)\n",
        "    row_count = len(df) \n",
        "    avg_sq_ft = int(df['sq__ft'].sum()) / row_count\n",
        "    #print(f'row_count: {row_count}, avg_sq_ft: {avg_sq_ft}')\n",
        "\n",
        "    df_zip_95670 = df[df['zip'] == 95670]\n",
        "    df_zip_not_95610 = df[df['zip'] != 95610]\n",
        "\n",
        "    # ------ Place code above here /\\ /\\ /\\ ------\n",
        "\n",
        "    return df, row_count, avg_sq_ft, df_zip_95670, df_zip_not_95610\n",
        "\n",
        "\n",
        "def exercise10(n):\n",
        "    # Create a numpy identity matrix of size n\n",
        "    # ------ Place code below here \\/ \\/ \\/ ------\n",
        "    np.identity(n)\n",
        "    \n",
        "\n",
        "    # ------ Place code above here /\\ /\\ /\\ ------  \n",
        "    identity_matrix = np.identity(n)\n",
        "\n",
        "    return identity_matrix\n",
        "    \n",
        "#print(exercise10(5))\n",
        "\n",
        "def exercise11(n):\n",
        "    '''\n",
        "    Using NumPy, create a single dimension array, array_1d, of size n containing integers 0 to n-1\n",
        "    Reshape the array. The reshaped array, array_reshaped, should be n/3 columns and 3 rows\n",
        "    '''\n",
        "    # ------ Place code below here \\/ \\/ \\/ ------\n",
        "    array_1d = np.arange(n)\n",
        "    array_reshaped = np.reshape(array_1d,[3,-1])  \n",
        "    \n",
        "\n",
        "    # ------ Place code above here /\\ /\\ /\\ ------  \n",
        "\n",
        "    return array_1d, array_reshaped\n",
        "\n",
        "#print(exercise11(27))    \n",
        "\n",
        "\n",
        "def exercise12(n):\n",
        "    '''\n",
        "    Create a checkerboard NumPy matrix of size 2n x 2n using one line of code\n",
        "    A checkerboard matrix is a matrix with alternating 1s and 0s across rows and columns with the top left value equal to 1\n",
        "    '''\n",
        "    # ------ Place code below here \\/ \\/ \\/ ------\n",
        "    board_size = 2*n \n",
        "    checkerboard_matrix = np.ones((board_size, board_size), dtype=int)\n",
        "    #slicing, start: end: step\n",
        "    #to assign zero to odd rows and even cloumns\n",
        "    checkerboard_matrix[1::2,::2]=0\n",
        "    #to assign zeros to even rows\n",
        "    checkerboard_matrix[::2,1::2]=0\n",
        "\n",
        "    # ------ Place code above here /\\ /\\ /\\ ------ \n",
        "\n",
        "    #checkerboard_matrix = None\n",
        "    return checkerboard_matrix\n",
        "\n",
        "#print(exercise12(6))    \n",
        "\n",
        "\n",
        "from pandas._config import dates\n",
        "def exercise13(n):\n",
        "    '''\n",
        "    Create a pandas Series, s, with n random integers between 0 and n, for n days starting from 1/1/2010 and plot the\n",
        "    cumulative sum on a  chart. The data range should be an index. pd.date_range() may help. \n",
        "    \n",
        "    '''\n",
        "    # ------ Place code below here \\/ \\/ \\/ ------\n",
        "    s_start_date = pd.Timestamp(\"2010-01-01 00:00:00\")\n",
        "    dates_range = pd.date_range(s_start_date, periods=n)\n",
        "    #print(dates_range)\n",
        "    s = pd.Series(np.random.randint(0,n,n), index=dates_range)\n",
        "    print(s)\n",
        "\n",
        "    ummulative_sum=[0]\n",
        "    i = 0\n",
        "    for value in s:\n",
        "      # was (parenthesis around cummulative_sum)\n",
        "      # cummulative_sum.append(cummulative_sum[-1])+value\n",
        "      # should be (parenthesis after value)\n",
        "      cummulative_sum.append(cummulative_sum[-1]+value) \n",
        "    cummulative_sum = cummulative_sum[1:]\n",
        "    plt.plot(dates_range, cummulative_sum,\"r+\")\n",
        "    plt.show()\n",
        "\n",
        "    # ------ Place code above here /\\ /\\ /\\ ------ \n",
        "    #s = None\n",
        "\n",
        "    return s\n",
        "\n",
        "\n",
        "    def exercise14(words):\n",
        "    '''\n",
        "    Exercise14() receives a Python list of words. Create and return a pandas DataFrame or Series that tabulates the length of \n",
        "    each word i.e. a list of the words hello, car, bye would produce a DataFrame with 3 rows and a column with the numbers 5,3,3\n",
        "    Using Series.map() and lambdas may help.\n",
        "    '''\n",
        "    # ------ Place code below here \\/ \\/ \\/ ------\n",
        "    df = pd.DataFrame(words)\n",
        "    df[\"word_length\"]=0\n",
        "    df[\"word_length\"]=df[0].apply(lambda x:pd.Series(len(x)))\n",
        "\n",
        "\n",
        "    # ------ Place code above here /\\ /\\ /\\ ------ \n",
        "    #df = None\n",
        "    return df\n",
        "\n",
        "    def exercise15():\n",
        "    '''\n",
        "    Use the real estate transaction DataFrame from Exercise 8 and extract into a new DataFrame every 5th row using iloc \n",
        "    and just the street address and zip code columns. This can be done with one line of code.\n",
        "    '''\n",
        "    # ------ Place code below here \\/ \\/ \\/ ------\n",
        "    df =  pd.read_csv(\"https://tinyurl.com/y63q7okz\", header=0)\n",
        "    #df_new = df[::5] # every 5th row\n",
        "    df_new = pd.DataFrame(df[::5],columns =['street', 'zip']) # specify columns\n",
        "    print(df_new.head)\n",
        "\n",
        "    # ------ Place code above here /\\ /\\ /\\ ------ \n",
        "    df = None\n",
        "    return df\n",
        "\n",
        "class TestAssignment5(unittest.TestCase):\n",
        "    def test_exercise15(self):\n",
        "        print('Skipping exercise 15')\n",
        "        df = exercise15()\n",
        "        print(df)\n",
        "    \n",
        "    def test_exercise14(self):\n",
        "        print('Skipping exercise 14')\n",
        "        df = exercise14(['cat','frog','walrus','antelope'])\n",
        "        print(df)\n",
        "\n",
        "\n",
        "    def test_exercise13(self):\n",
        "        print('Testing exercise 13')\n",
        "        s= exercise13(1000)\n",
        "        self.assertEqual(s.index[0],pd.Timestamp('2010-01-01 00:00:00'))\n",
        "        self.assertEqual(len(s.index),1000)\n",
        "\n",
        "\n",
        "    def test_exercise12(self):\n",
        "        print('Testing exercise 12')\n",
        "        cm = exercise12(10)\n",
        "        self.assertEqual(cm.shape[0],20)\n",
        "        self.assertEqual(cm[0,0],1)\n",
        "        self.assertEqual(cm[0,1],0)\n",
        "        cm = exercise12(5)\n",
        "        self.assertEqual(cm.shape[0],10)\n",
        "        self.assertEqual(cm[0,0],1)\n",
        "        self.assertEqual(cm[0,1],0)        \n",
        "\n",
        "    def test_exercise11(self):\n",
        "        print('Testing exercise 11')\n",
        "        a1d, ar = exercise11(15)\n",
        "        self.assertEqual(a1d.shape[0],15)\n",
        "        self.assertEqual(ar.shape[0],3)\n",
        "        self.assertEqual(ar.shape[1],5)\n",
        "\n",
        "\n",
        "    def test_exercise10(self):\n",
        "        print('Testing exercise 10')\n",
        "        im = exercise10(10)\n",
        "        self.assertEqual(im.shape[0],10)\n",
        "        self.assertEqual(im.shape[1],10)     \n",
        "\n",
        "\n",
        "    def test_exercise08(self):\n",
        "        print('Testing exercise 8')\n",
        "        df, row_count, avg_sq_ft, df_zip_95670, df_zip_not_95610 = exercise08()\n",
        "        self.assertEqual(df.shape[0],985)\n",
        "        self.assertEqual(df.shape[1],12)\n",
        "        self.assertEqual(row_count,985)\n",
        "        self.assertAlmostEqual(avg_sq_ft,1314.91675127,2)\n",
        "        self.assertEqual(df_zip_95670.shape[0],21)\n",
        "        self.assertEqual(df_zip_not_95610.shape[0],978)\n",
        " \n",
        "    \n",
        "    def test_exercise07(self):\n",
        "        print('Testing exercise 7')\n",
        "        z = exercise07(10,5,100000)\n",
        "        self.assertEqual(z.shape[0], 100000)\n",
        "        self.assertLessEqual(np.average(z), 5.2)\n",
        "        self.assertGreaterEqual(np.average(z), 4.7)\n",
        "        z = exercise07(5,10,100000)\n",
        "        self.assertEqual(z.shape[0], 100000)\n",
        "        self.assertLessEqual(np.average(z), 10.2)\n",
        "        self.assertGreaterEqual(np.average(z), 9.7)\n",
        "\n",
        "\n",
        "    def test_exercise06(self):\n",
        "        print('Testing exercise 6')\n",
        "        z = exercise06(7).shape\n",
        "        self.assertEqual(z[0], 7)\n",
        "        self.assertEqual(z[1], 7)\n",
        "        z = exercise05(70).shape\n",
        "        self.assertEqual(z[0], 70)\n",
        "        self.assertEqual(z[1], 70)\n",
        "\n",
        "    def test_exercise05(self):\n",
        "        print('Testing exercise 5')\n",
        "        z = exercise05(7).shape\n",
        "        self.assertEqual(z[0], 7)\n",
        "        self.assertEqual(z[1], 7)\n",
        "        z = exercise05(70).shape\n",
        "        self.assertEqual(z[0], 70)\n",
        "        self.assertEqual(z[1], 70)\n",
        "\n",
        "    def test_exercise04(self):\n",
        "        print('Testing exercise 4')\n",
        "        array = np.array([[1,1,1,1,1],[0,2,0,0,1]])\n",
        "        sum = exercise04(array)\n",
        "        self.assertEqual(sum, 3)\n",
        "        array = np.array([[1,6,1,1,1],[0,2,0,0,1]])\n",
        "        sum = exercise04(array)\n",
        "        self.assertEqual(sum, 8)\n",
        "\n",
        "    def test_exercise03(self):\n",
        "        print('Testing exercise 3')\n",
        "        array = np.array([1,1,1,1,1])\n",
        "        sum = exercise03(array)\n",
        "        self.assertEqual(sum, 5)\n",
        "        array = np.array([2,4])\n",
        "        sum = exercise03(array)\n",
        "        self.assertEqual(sum, 6)\n",
        "\n",
        "    def test_exercise01(self):\n",
        "        print('Testing exercise 1')\n",
        "        m = exercise01().shape\n",
        "        self.assertEqual(m[0], 3)\n",
        "        self.assertEqual(m[1], 4)\n",
        "\n",
        "    def test_exercise02(self):\n",
        "        print('Testing exercise 2')\n",
        "        m = exercise02([1,2,3,4,5,6])\n",
        "        self.assertTrue(type(m) is np.ndarray)\n",
        "        self.assertEqual(m.shape[0], 6)\n",
        "\n",
        "\n",
        "ta.test_exercise01()\n",
        "ta.test_exercise02()\n",
        "ta.test_exercise03()\n",
        "ta.test_exercise04()\n",
        "ta.test_exercise05()\n",
        "ta.test_exercise06()\n",
        "ta.test_exercise07()\n",
        "ta.test_exercise08()\n",
        "ta.test_exercise10()\n",
        "ta.test_exercise11()\n",
        "ta.test_exercise12()\n",
        "ta.test_exercise13()\n",
        "ta.test_exercise14()\n",
        "ta.test_exercise15()\n",
        "\n",
        "\n",
        "\n"
      ]
    }
  ]
}